# Numpy Array

In [4]:
import numpy as np

In [5]:
np.array([1,2,3])

array([1, 2, 3])

In [6]:
type(np.array([1,2,3]))

numpy.ndarray

In [7]:
np.array([1,2,4.0])

array([1., 2., 4.])

In [8]:
a=np.array([[1,2],[3,4]])

In [9]:
a.shape # how to check dimentions array

(2, 2)

In [10]:
#Minimum dimenstions 2:

In [11]:
np.array([1,2,3],ndmin=2)

array([[1, 2, 3]])

In [12]:
np.array([1,2,3], dtype=complex) # complex is combinnation of real number as well as imaginary number

array([1.+0.j, 2.+0.j, 3.+0.j])

In [13]:
x = np.array([(1,2),(3,5)],dtype=[('a','<i4'),('b','<i4')]) 

dtype=[('a','<i4'),('b','<i4')])  big big endian and little endian basically its a arangement of bits.and its arrangemnet of a calculation which happens inside our cumputor based.

In [14]:
x

array([(1, 2), (3, 5)], dtype=[('a', '<i4'), ('b', '<i4')])

In [15]:
x[0][0]

1

In [16]:
type(x[0][0])

numpy.int32

In [17]:
x['a']

array([1, 3], dtype=int32)

In [18]:
x['b']

array([2, 5], dtype=int32)

In [19]:
np.array(np.mat('1 2;3 4;5 6;7 8'), subok=True) 

matrix([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])

In [20]:
type(np.array(np.mat('1 2;3 4;5 6;7 8'), subok=True))

numpy.matrix

# numpy.asarray

In [21]:
a

array([[1, 2],
       [3, 4]])

In [22]:
a[0][::-1]

array([2, 1])

In [23]:
a[0][0]

1

In [24]:
np.asarray(a)

array([[1, 2],
       [3, 4]])

In [25]:
type(np.asarray(a))

numpy.ndarray

# numpy.asanyarray

In [26]:
a=[3,5]
b=np.asanyarray(a)
type(b)

numpy.ndarray

In [27]:
a=np.matrix([4,5])

In [28]:
np.asanyarray(a)

matrix([[4, 5]])

In [29]:
#Create an array x, with a reference y and a copy z:

In [30]:
x=np.array([4,5,6,7,8])

In [31]:
y=x
y

array([4, 5, 6, 7, 8])

In [32]:
y[0]=2 # array in inmutable property 

In [33]:
y

array([2, 5, 6, 7, 8])

In [34]:
x

array([2, 5, 6, 7, 8])

In [35]:
z=np.copy(x)

In [36]:
#when we modify x, y changes, but not z

In [37]:
y[0] = 100
x

array([100,   5,   6,   7,   8])

In [38]:
x

array([100,   5,   6,   7,   8])

In [39]:
id(x[0])

140419728947912

In [40]:
z

array([2, 5, 6, 7, 8])

# numpy.fromfunction

In [41]:
#Construct an array by executing a function over each coordinate.

In [42]:
np.fromfunction(lambda i, j:i ==j,(4,6),dtype=int)

array([[ True, False, False, False, False, False],
       [False,  True, False, False, False, False],
       [False, False,  True, False, False, False],
       [False, False, False,  True, False, False]])

In [43]:
 np.fromfunction(lambda i, j: i * j, (3, 3), dtype=int)

array([[0, 0, 0],
       [0, 1, 2],
       [0, 2, 4]])

In [44]:
np.fromfunction(lambda i, j: i + j, (3, 3), dtype=int)

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [45]:
#Create a new 1-dimensional array from an iterable object.

In [46]:
range(199)  # range basically interable function

range(0, 199)

In [47]:
type(range(199))

range

In [48]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [49]:
np.array(list(range(15))) 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [50]:
np.asanyarray(list(range(15))) 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [51]:
iterable=(x8x for x in range (5))

In [52]:
np.fromiter(range(20),int)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [53]:
#A new 1-D array initialized from text data in a string

In [54]:
a = np.fromstring('234 234',sep=' ')
a

array([234., 234.])

# data types

In [55]:
my_list=[1,2,3,4,5]
import numpy as np
arr=np.array(my_list)
arr

array([1, 2, 3, 4, 5])

In [56]:
arr.ndim # how to check dimenstions of array

1

In [57]:
my_list=[1,2,3,4,5]
import numpy as np
a=np.array(my_list,ndmin=2)
a.ndim

2

In [58]:
a.size

5

In [59]:
a.shape

(1, 5)

In [60]:
a.dtype

dtype('int64')

In [61]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]
mat = np.array(my_mat)

In [62]:
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [63]:
my_list = [1,2,3]
import numpy as np
arr = np.array(my_list)
print("Type/Class of this object:",type(arr))
print("Here is the vector\n--------------------\n",arr)

Type/Class of this object: <class 'numpy.ndarray'>
Here is the vector
--------------------
 [1 2 3]


In [64]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]
mat = np.array(my_mat)
print("Type/Class of this object:",type(mat))
print("Here is the matrix\n----------\n",mat,"\n----------")
print("Dimension of this matrix: ",mat.ndim,sep='') #ndim gives the dimensison, 2 for a matrix, 1 for a vector
print("Size of this matrix: ", mat.size,sep='') #size gives the total number of elements
print("Shape of this matrix: ", mat.shape,sep='') #shape gives the number of elements along each axes (dimension)
print("Data type of this matrix: ", mat.dtype,sep='') #dtype gives the data type contained in the array


Type/Class of this object: <class 'numpy.ndarray'>
Here is the matrix
----------
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 
----------
Dimension of this matrix: 2
Size of this matrix: 9
Shape of this matrix: (3, 3)
Data type of this matrix: int64


In [65]:
my_mat = [[1.1,2,3],[4,5.2,6],[7,8.3,9]]
mat = np.array(my_mat)
print("Data type of the modified matrix: ", mat.dtype,sep='') #dtype gives the data type contained in the array
print("\n\nEven tuples can be converted to ndarrays...")


Data type of the modified matrix: float64


Even tuples can be converted to ndarrays...


In [66]:
b = np.array([(1.5,2,3), (4,5,6)])
print("We write b = np.array([(1.5,2,3), (4,5,6)])")
print("Matrix made from tuples, not lists\n---------------------------------------")
print(b)

We write b = np.array([(1.5,2,3), (4,5,6)])
Matrix made from tuples, not lists
---------------------------------------
[[1.5 2.  3. ]
 [4.  5.  6. ]]


# arange and linspace

In [67]:
list(range(10.34))

TypeError: 'float' object cannot be interpreted as an integer

In [68]:
np.arange(13.56)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13.])

In [69]:
print("A series of numbers:",type(np.arange(5,16)))
np.arange(5,16,2.3)# A series of numbers from low to high

A series of numbers: <class 'numpy.ndarray'>


array([ 5. ,  7.3,  9.6, 11.9, 14.2])

In [70]:
list(range(5,16,2))


[5, 7, 9, 11, 13, 15]

In [71]:
list(range(50,-1,5))

[]

In [72]:
print("Numbers spaced apart by float:",np.arange(0,11,2.5)) # Numbers spaced apart by 2.5

Numbers spaced apart by float: [ 0.   2.5  5.   7.5 10. ]


In [73]:
print("Numbers spaced apart by 2:",np.arange(50,-1,5)) # Numbers spaced apart by 2

Numbers spaced apart by 2: []


In [74]:
print("Every 5th number from 50 in reverse order\n",np.arange(5.0,-1,-5))

Every 5th number from 50 in reverse order
 [5. 0.]


In [75]:
print("21 linearly spaced numbers between 1 and 5\n--------------------------------------------")
print((np.linspace(1,5,50)))

21 linearly spaced numbers between 1 and 5
--------------------------------------------
[1.         1.08163265 1.16326531 1.24489796 1.32653061 1.40816327
 1.48979592 1.57142857 1.65306122 1.73469388 1.81632653 1.89795918
 1.97959184 2.06122449 2.14285714 2.2244898  2.30612245 2.3877551
 2.46938776 2.55102041 2.63265306 2.71428571 2.79591837 2.87755102
 2.95918367 3.04081633 3.12244898 3.20408163 3.28571429 3.36734694
 3.44897959 3.53061224 3.6122449  3.69387755 3.7755102  3.85714286
 3.93877551 4.02040816 4.10204082 4.18367347 4.26530612 4.34693878
 4.42857143 4.51020408 4.59183673 4.67346939 4.75510204 4.83673469
 4.91836735 5.        ]


# Matrix creation

In [76]:
print("Vector of zeroes\n---------------------")
print(np.zeros(50))

Vector of zeroes
---------------------
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0.]


In [77]:
print("Matrix of zeroes\n--------------------")
print(np.zeros((3,4))) # Notice Tuples

Matrix of zeroes
--------------------
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [78]:
print("Matrix of zeroes\n--------------------")
print(np.zeros((7,4,5))) # Notice Tuples

Matrix of zeroes
--------------------
[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


In [79]:
 print("Vector of ones\n---------------------")
print(np.ones(9))  # is going to create an array  with all one so here i am trying to call numpy trying pass a dimenstion

Vector of ones
---------------------
[1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [80]:
print("Matrix of ones\n---------------------")
print(np.ones((5,2,8))) # Note matrix dimension specified by Tuples


Matrix of ones
---------------------
[[[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]]


In [81]:
print("Matrix of 5's\n---------------------")
print(5+np.ones((3,5)))

Matrix of 5's
---------------------
[[6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]]


In [82]:
print("Empty matrix\n-------------\n", np.empty((3,5)))

Empty matrix
-------------
 [[6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]]


In [83]:
mat1 = np.eye(4) 
print("Identity matrix of dimension", mat1.shape)
print(mat1)

Identity matrix of dimension (4, 4)
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [84]:
np.arange(3) 

array([0, 1, 2])

In [85]:
 np.arange(3,7)

array([3, 4, 5, 6])

In [86]:
np.arange(3,7,2)

array([3, 5])

In [87]:
np.linspace(2.0, 3.0, num=5)


array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [88]:
# how many number i wnat to generate in between starting point and end point 
np.linspace(2.0, 3.0, num=5, endpoint=False)

array([2. , 2.2, 2.4, 2.6, 2.8])

In [89]:
np.linspace(2.0, 3.0, num=9, retstep=True)

(array([2.   , 2.125, 2.25 , 2.375, 2.5  , 2.625, 2.75 , 2.875, 3.   ]), 0.125)

In [90]:
#Return numbers spaced evenly on a log scale.
np.linspace(2.0, 3.0, num=4)

array([2.        , 2.33333333, 2.66666667, 3.        ])

In [91]:
np.logspace(2.0, 3.0, num=4,base = 10)

array([ 100.        ,  215.443469  ,  464.15888336, 1000.        ])

In [92]:
np.logspace(2.0, 3.0, num=4, endpoint=False)

array([100.        , 177.827941  , 316.22776602, 562.34132519])

In [111]:

np.logspace(2.0, 3.0, num=4, base=2.0)

array([4.        , 5.0396842 , 6.34960421, 8.        ])

In [94]:
#Extract a diagonal or construct a diagonal array.

In [95]:
x = np.arange(16).reshape((-1,4))

In [96]:
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [97]:
np.diag(x)

array([ 0,  5, 10, 15])

In [113]:
np.diag(x, k=1
       )

array([ 1,  6, 11])

In [99]:
np.diag(x, k=-1)

array([ 4,  9, 14])

In [100]:
np.diag(np.diag(x))

array([[ 0,  0,  0,  0],
       [ 0,  5,  0,  0],
       [ 0,  0, 10,  0],
       [ 0,  0,  0, 15]])

In [101]:
#Create a two-dimensional array with the flattened input as a diagonal.

In [102]:
np.diagflat([[1,2], [3,4]])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [103]:
np.diagflat([1,2], 1)

array([[0, 1, 0],
       [0, 0, 2],
       [0, 0, 0]])

In [104]:
#An array with ones at and below the given diagonal and zeros elsewhere.

In [115]:
np.tri(3, 5, 1, dtype=int)

array([[1, 1, 0, 0, 0],
       [1, 1, 1, 0, 0],
       [1, 1, 1, 1, 0]])

In [106]:
np.tri(3, 5,k=-1)

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0.]])

In [107]:
#return a Lower triangle of an array.

In [108]:
np.tril([[1,2,3],[4,5,6],[7,8,9]], 0)

array([[1, 0, 0],
       [4, 5, 0],
       [7, 8, 9]])

In [109]:
#return Upper triangle of an array.

In [110]:
np.triu([[1,2,3],[4,5,6],[7,8,9],[10,11,12]], 1)

array([[0, 2, 3],
       [0, 0, 6],
       [0, 0, 0],
       [0, 0, 0]])

# Random number generation

In [116]:
print("Random number generation (from Uniform distribution)")
print(np.random.rand(2,3)) # 2 by 3 matrix with random numbers ranging from 0 to 1, Note no Tuple is necessary 

Random number generation (from Uniform distribution)
[[0.28187275 0.5249255  0.41530497]
 [0.29362907 0.12138958 0.95693682]]


In [174]:
np.random.rand(2,3,5)

array([[[0.45582544, 0.93860506, 0.39082688, 0.25673722, 0.49602199],
        [0.26243597, 0.95066836, 0.47584777, 0.2243754 , 0.30979423],
        [0.53263445, 0.00169352, 0.34517835, 0.05161168, 0.49272804]],

       [[0.77069592, 0.79964867, 0.20273866, 0.79415591, 0.09775627],
        [0.08524381, 0.28530475, 0.33619072, 0.26913804, 0.02199632],
        [0.48187095, 0.52148323, 0.06575628, 0.09835244, 0.41416115]]])

In [117]:
print("Numbers from Normal distribution with zero mean and standard deviation 1 i.e. standard normal")
print(np.random.randn(4,3))

Numbers from Normal distribution with zero mean and standard deviation 1 i.e. standard normal
[[ 1.37531906 -0.68552958 -1.92915307]
 [ 0.55696537 -0.06265457 -0.09127942]
 [ 0.5106699   1.3740581   0.42971383]
 [ 0.12167613  1.10130104  0.17631793]]


In [118]:
print("Random integer vector:",np.random.randint(1,10)) #randint (low, high, # of samples to be drawn)
print ("\nRandom integer matrix")


Random integer vector: 6

Random integer matrix


In [119]:
print(np.random.randint(1,100,(4,4))) #randint (low, high, # of samples to be drawn in a tuple to form a matrix)
print("\n20 samples drawn from a dice throw:",np.random.randint(1,7,20)) # 20 samples drawn from a dice throw

[[67 40 67 37]
 [27 77 96 91]
 [86 25 65 64]
 [70 43 14 44]]

20 samples drawn from a dice throw: [4 6 5 5 6 5 1 1 1 3 1 5 4 1 2 4 4 4 1 1]


# Reshaping

In [120]:
from numpy.random import randint as ri
a = ri(1,100,30)
b = a.reshape(2,3,5)
c = a.reshape(6,-19878)
c

array([[99, 26, 56, 73, 30],
       [99, 42, 33,  1, 36],
       [68, 32, 83, 36, 61],
       [34, 59, 15,  9, 28],
       [84, 80,  5, 48, 49],
       [14, 79, 17, 54, 81]])

In [121]:
print ("Shape of a:", a.shape)
print ("Shape of b:", b.shape)
print ("Shape of c:", c.shape)


Shape of a: (30,)
Shape of b: (2, 3, 5)
Shape of c: (6, 5)


In [122]:
print("\na looks like\n",'-'*20,"\n",a,"\n",'-'*20)
print("\nb looks like\n",'-'*20,"\n",b,"\n",'-'*20)
print("\nc looks like\n",'-'*20,"\n",c,"\n",'-'*20)



a looks like
 -------------------- 
 [99 26 56 73 30 99 42 33  1 36 68 32 83 36 61 34 59 15  9 28 84 80  5 48
 49 14 79 17 54 81] 
 --------------------

b looks like
 -------------------- 
 [[[99 26 56 73 30]
  [99 42 33  1 36]
  [68 32 83 36 61]]

 [[34 59 15  9 28]
  [84 80  5 48 49]
  [14 79 17 54 81]]] 
 --------------------

c looks like
 -------------------- 
 [[99 26 56 73 30]
 [99 42 33  1 36]
 [68 32 83 36 61]
 [34 59 15  9 28]
 [84 80  5 48 49]
 [14 79 17 54 81]] 
 --------------------


In [123]:
A = ri(1,100,10) # Vector of random interegrs
print("\nVector of random integers\n",'-'*50,"\n",A)
print("\nHere is the sorted vector\n",'-'*50,"\n",np.sort(A))



Vector of random integers
 -------------------------------------------------- 
 [ 6 15 28 21 30 71 68 68 60  9]

Here is the sorted vector
 -------------------------------------------------- 
 [ 6  9 15 21 28 30 60 68 68 71]


In [124]:
M = ri(1,100,25).reshape(5,5) # Matrix of random interegrs
#print("\nHere is the sorted matrix along each row\n",'-'*50,"\n",np.sort(M, kind='mergesort')) # Default axis =1
print("\nHere is the sorted matrix along each column\n",'-'*50,"\n",np.sort(M, axis=1, kind='mergesort'))
M


Here is the sorted matrix along each column
 -------------------------------------------------- 
 [[ 8  8  9 39 68]
 [ 3 13 31 36 80]
 [ 1 41 62 70 82]
 [ 6 18 52 88 92]
 [10 44 81 96 99]]


array([[68,  8,  9, 39,  8],
       [80, 36,  3, 13, 31],
       [70, 82, 41,  1, 62],
       [92,  6, 52, 18, 88],
       [99, 81, 96, 44, 10]])

In [125]:
print("Max of a:", M.max())
print("Max of b:", b.max())
b

Max of a: 99
Max of b: 99


array([[[99, 26, 56, 73, 30],
        [99, 42, 33,  1, 36],
        [68, 32, 83, 36, 61]],

       [[34, 59, 15,  9, 28],
        [84, 80,  5, 48, 49],
        [14, 79, 17, 54, 81]]])

In [126]:
M

array([[68,  8,  9, 39,  8],
       [80, 36,  3, 13, 31],
       [70, 82, 41,  1, 62],
       [92,  6, 52, 18, 88],
       [99, 81, 96, 44, 10]])

In [127]:
print("Max of a location:", M.argmax(axis= 1 ))
print("Max of b location:", b.argmax())
print("Max of c location:", b.argmax())

Max of a location: [0 0 1 0 0]
Max of b location: 0
Max of c location: 0


# Indexing and slicing

In [128]:
arr = np.arange(0,11)
print("Array:",arr)


Array: [ 0  1  2  3  4  5  6  7  8  9 10]


In [129]:
print("Element at 7th index is:", arr[7])


Element at 7th index is: 7


In [130]:
print("Elements from 3rd to 5th index are:", arr[3:6:2])


Elements from 3rd to 5th index are: [3 5]


In [131]:
print("Elements up to 4th index are:", arr[:4])
arr

Elements up to 4th index are: [0 1 2 3]


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [132]:
print("Elements from last backwards are:", arr[-1:7:-1])


Elements from last backwards are: [10  9  8]


In [133]:
print("3 Elements from last backwards are:", arr[-1:-6:2])


3 Elements from last backwards are: []


In [134]:
arr = np.arange(0,21,2)
print("New array:",arr)


New array: [ 0  2  4  6  8 10 12 14 16 18 20]


In [135]:
print("Elements at 2nd, 4th, and 9th index are:", arr[[2,4,9]]) # Pass a list as a index to subset

Elements at 2nd, 4th, and 9th index are: [ 4  8 18]


In [136]:
import numpy as np 
mat = np.array(ri(10,100,15)).reshape(3,5)
print("Matrix of random 2-digit numbers\n--------------------------------\n",mat)
mat[1:4,3:5]
mat[0:3,[1,3]]

Matrix of random 2-digit numbers
--------------------------------
 [[55 39 52 47 76]
 [21 91 27 47 15]
 [21 31 70 23 90]]


array([[39, 47],
       [91, 47],
       [31, 23]])

In [137]:
mat[0:3,[1,3]]
mat

array([[55, 39, 52, 47, 76],
       [21, 91, 27, 47, 15],
       [21, 31, 70, 23, 90]])

In [138]:
print("\nDouble bracket indexing\n------------------------")
print("Element in row index 1 and column index 2:", mat[1][1])
mat


Double bracket indexing
------------------------
Element in row index 1 and column index 2: 91


array([[55, 39, 52, 47, 76],
       [21, 91, 27, 47, 15],
       [21, 31, 70, 23, 90]])

In [139]:
print("\nSingle bracket with comma indexing\n----------------------------------")
print("Element in row index 1 and column index 2:", mat[1,2])
print("\nRow or column extract\n----------------------")



Single bracket with comma indexing
----------------------------------
Element in row index 1 and column index 2: 27

Row or column extract
----------------------


In [140]:
print("Entire row at index 2:", mat[2])
print("Entire column at index 3:", mat[:,3])


Entire row at index 2: [21 31 70 23 90]
Entire column at index 3: [47 47 23]


In [141]:
print("\nSubsetting sub-matrices\n--------------------------")
print("Matrix with row indices 1 and 2 and column indices 3 and 4\n", mat[1:3,3:5])



Subsetting sub-matrices
--------------------------
Matrix with row indices 1 and 2 and column indices 3 and 4
 [[47 15]
 [23 90]]


In [142]:
print("Matrix with row indices 0 and 1 and column indices 1 and 3\n", mat[0:2,[1,3]])

Matrix with row indices 0 and 1 and column indices 1 and 3
 [[39 47]
 [91 47]]


# Subseting

In [143]:
mat = np.array(ri(10,100,15)).reshape(3,5)
print("Matrix of random 2-digit numbers\n--------------------------------\n",mat)
mat>50

Matrix of random 2-digit numbers
--------------------------------
 [[41 40 44 87 36]
 [49 65 44 16 20]
 [49 74 64 20 91]]


array([[False, False, False,  True, False],
       [False,  True, False, False, False],
       [False,  True,  True, False,  True]])

In [144]:
print ("Elements greater than 50\n", mat[mat>50])

Elements greater than 50
 [87 65 74 64 91]


# Slicing

In [145]:
mat = np.array([[11,12,13],[21,22,23],[31,32,33]])
print("Original matrix")
print(mat)


Original matrix
[[11 12 13]
 [21 22 23]
 [31 32 33]]


In [146]:
mat_slice = mat[:2,:2]
print ("\nSliced matrix")
print(mat_slice)
print ("\nChange the sliced matrix")


Sliced matrix
[[11 12]
 [21 22]]

Change the sliced matrix


In [147]:
mat_slice[0,0] = 1000
print (mat_slice)

[[1000   12]
 [  21   22]]


In [148]:
print("\nBut the original matrix? WHOA! It got changed too!")
print(mat)



But the original matrix? WHOA! It got changed too!
[[1000   12   13]
 [  21   22   23]
 [  31   32   33]]


In [149]:
# Little different way to create a copy of the slixed matrix
print ("\nDoing it again little differently now...\n")
mat = np.array([[11,12,13],[21,22,23],[31,32,33]])
print("Original matrix")
print(mat)



Doing it again little differently now...

Original matrix
[[11 12 13]
 [21 22 23]
 [31 32 33]]


In [150]:
mat_slice = np.array(mat[:2,:2]) # Notice the np.array command to create a new array not just slicing
print ("\nSliced matrix")
print(mat_slice)



Sliced matrix
[[11 12]
 [21 22]]


In [151]:
print ("\nChange the sliced matrix")
mat_slice[0,0] = 1000
print (mat_slice)



Change the sliced matrix
[[1000   12]
 [  21   22]]


In [152]:
print("\nBut the original matrix? NO CHANGE this time:)")
print(mat)


But the original matrix? NO CHANGE this time:)
[[11 12 13]
 [21 22 23]
 [31 32 33]]


# Universal Functions

In [153]:
mat1 = np.array(ri(1,10,9)).reshape(3,3)
mat2 = np.array(ri(1,10,9)).reshape(3,3)
print("\n1st Matrix of random single-digit numbers\n----------------------------------------\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n----------------------------------------\n",mat2)



1st Matrix of random single-digit numbers
----------------------------------------
 [[8 6 4]
 [2 7 9]
 [1 1 4]]

2nd Matrix of random single-digit numbers
----------------------------------------
 [[6 8 8]
 [2 7 1]
 [7 8 3]]


In [154]:
mat1*mat2

array([[48, 48, 32],
       [ 4, 49,  9],
       [ 7,  8, 12]])

In [155]:
#print("\nAddition\n------------------\n", mat1+mat2)
print("\nMultiplication\n------------------\n", mat1@mat2)



Multiplication
------------------
 [[ 88 138  82]
 [ 89 137  50]
 [ 36  47  21]]


In [156]:
print("\nDivision\n------------------\n", mat1/0)
#print("\nLineaer combination: 3*A - 2*B\n-----------------------------\n", 3*mat1-2*mat2)



Division
------------------
 [[inf inf inf]
 [inf inf inf]
 [inf inf inf]]


/home/puru/.local/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


In [157]:
print("\nAddition of a scalar (100)\n-------------------------\n", 100+mat1)



Addition of a scalar (100)
-------------------------
 [[108 106 104]
 [102 107 109]
 [101 101 104]]


In [158]:
print("\nExponentiation, matrix cubed here\n----------------------------------------\n", mat1**3)
print("\nExponentiation, sq-root using pow function\n-------------------------------------------\n",pow(mat1,3))


Exponentiation, matrix cubed here
----------------------------------------
 [[512 216  64]
 [  8 343 729]
 [  1   1  64]]

Exponentiation, sq-root using pow function
-------------------------------------------
 [[512 216  64]
 [  8 343 729]
 [  1   1  64]]


# Broadcasting

In [159]:
#NumPy operations are usually done on pairs of arrays on an element-by-element basis. 
#In the simplest case, the two arrays must have exactly the same shape.
#NumPy’s broadcasting rule relaxes this constraint when the arrays’ shapes meet certain constraints. 
#When operating on two arrays, NumPy compares their shapes element-wise. It starts with the trailing 
#dimensions, and works its way forward. Two dimensions are compatible when
#they are equal, or one of them is 1

In [160]:
start = np.zeros((4,4))
start= start+100
start

array([[100., 100., 100., 100.],
       [100., 100., 100., 100.],
       [100., 100., 100., 100.],
       [100., 100., 100., 100.]])

In [161]:
# create a rank 1 ndarray with 3 values
add_rows = np.array([1, 0, 2,5])
print(add_rows)

[1 0 2 5]


In [162]:
y = start + add_rows  # add to each row of 'start' using broadcasting
print(y)

[[101. 100. 102. 105.]
 [101. 100. 102. 105.]
 [101. 100. 102. 105.]
 [101. 100. 102. 105.]]


In [163]:
# create an ndarray which is 4 x 1 to broadcast across columns
add_cols = np.array([[0,1,2,3]])
add_cols = add_cols.T
print(add_cols)

[[0]
 [1]
 [2]
 [3]]


In [164]:
# add to each column of 'start' using broadcasting
y = start + add_cols 
print(y)

[[100. 100. 100. 100.]
 [101. 101. 101. 101.]
 [102. 102. 102. 102.]
 [103. 103. 103. 103.]]


In [165]:
# this will just broadcast in both dimensions
add_scalar = np.array([100])  
print(start+y)

[[200. 200. 200. 200.]
 [201. 201. 201. 201.]
 [202. 202. 202. 202.]
 [203. 203. 203. 203.]]


# Array Math

In [166]:
mat1 = np.array(ri(1,10,9)).reshape(3,3)
mat2 = np.array(ri(1,10,9)).reshape(3,3)
print("\n1st Matrix of random single-digit numbers\n\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n------------\n",mat2)



1st Matrix of random single-digit numbers

 [[1 8 6]
 [2 5 1]
 [5 9 2]]

2nd Matrix of random single-digit numbers
------------
 [[3 3 7]
 [3 3 9]
 [3 1 3]]


In [167]:
print("\nSq-root of 1st matrix using np\n------------------\n", np.sqrt(mat1))



Sq-root of 1st matrix using np
------------------
 [[1.         2.82842712 2.44948974]
 [1.41421356 2.23606798 1.        ]
 [2.23606798 3.         1.41421356]]


In [168]:
print("\nExponential power of 1st matrix using np\n",'-'*50,"\n", np.exp(mat1))



Exponential power of 1st matrix using np
 -------------------------------------------------- 
 [[2.71828183e+00 2.98095799e+03 4.03428793e+02]
 [7.38905610e+00 1.48413159e+02 2.71828183e+00]
 [1.48413159e+02 8.10308393e+03 7.38905610e+00]]


In [169]:
print("\n10-base logarithm on 1st matrix using np\n",'-'*50,"\n", np.log10(mat1))
print(mat1)
print(mat2)


10-base logarithm on 1st matrix using np
 -------------------------------------------------- 
 [[0.         0.90308999 0.77815125]
 [0.30103    0.69897    0.        ]
 [0.69897    0.95424251 0.30103   ]]
[[1 8 6]
 [2 5 1]
 [5 9 2]]
[[3 3 7]
 [3 3 9]
 [3 1 3]]


In [170]:
print("\nModulo reminder using np\n",'-'*50,"\n", np.fmod(mat1,mat2))
mat1%mat2


Modulo reminder using np
 -------------------------------------------------- 
 [[1 2 6]
 [2 2 1]
 [2 0 2]]


array([[1, 2, 6],
       [2, 2, 1],
       [2, 0, 2]])

In [171]:
print("\nCombination of functions by shwoing exponetial decay of a sine wave\n",'-'*70)



Combination of functions by shwoing exponetial decay of a sine wave
 ----------------------------------------------------------------------


In [172]:
A = np.linspace(0,12*np.pi,1001)


In [173]:
A

array([ 0.        ,  0.03769911,  0.07539822, ..., 37.62371362,
       37.66141273, 37.69911184])